stages:
  - test
  - docker
  - doc 

#-----------------
# Tests
#-----------------

.tests:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: test
  script:
    # XXX shell runned with gitlab runner are not
    # sourcing ~/.bashrc (but works with `docker run ...`)
    - source ~/.bashrc
    - make install install-tests
    - pip list -l
    - make test
  tags:   
    - factory

tests:ltr: 
  extends: .tests
  variables:
    QGIS_FLAVOR: ltr

tests:release: 
  extends: .tests
  needs:    
    - "tests:ltr"
  variables:
    QGIS_FLAVOR: release

doc:
  stage: doc
  script: 
    - make -C doc
    - $FACTORY_SCRIPTS/deploy-doc doc/build/html/ doc/doc.manifest
  tags:
    - factory-plain
  only:
    refs:
    - tags
    - main

# Docker build
include: '/docker/.gitlab-ci.yml'

  

