services:

  worker:
    image: 3liz/qgis-services:release-eager
    networks:
    - qgis_rpc_network
    hostname: worker
    environment:
      CONF_DISPLAY_XVFB: ON
      CONF_CONFIG_URL__URL: "http://config-server/config_worker.json"
    volumes:
    - { type: bind, source: "${PWD}/tests/", target: /opt/qgis-services }
    - { type: volume, target: /srv/vol1 }
    command: ["qgis-server-rpc", "serve"]
    depends_on:
    - config-server

  web:
    image: 3liz/qgis-services:release-eager
    environment:
      CONF_CONFIG_URL__URL: "http://config-server/config_proxy.json"
    ports:
    - 127.0.0.1:4000:80
    - 127.0.0.1:9876:9876
    networks:
    - qgis_rpc_network
    command: ["qgis-server-http", "serve", "--verbose"]
    profiles:
    - web
    depends_on:
    - config-server

  config-server:
    image: nginx:alpine
    networks:
    - qgis_rpc_network
    ports:
    - 127.0.0.1:8004:80
    volumes:
    - type: bind
      source: "${PWD}/tests/"
      target: /usr/share/nginx/html
      read_only: true

  amqp:
    image: rabbitmq:3
    networks:
    - qgis_rpc_network
    profiles:
    - amqp


networks:
  qgis_rpc_network:
    driver: bridge
