version: "3.9"

services:

  worker:
    image: qgis-services:release
    networks:
    - qgis_rpc_network
    environment: 
      CONF_CONFIG_URL__URL: "http://config-server/config_worker.json"
    volumes:
    - { type: bind, source: "${PWD}/tests/", target: /opt/qgis-services }
    command: ["qgis-server-rpc", "serve"]

  proxy:
    image: qgis-services:release
    environment:
      CONF_DISPLAY_XVFB: OFF
      CONF_CONFIG_URL__URL: "http://config-server/config_proxy.json"
    ports:
    - 127.0.0.1:8003:80
    networks:
    - qgis_rpc_network
    command: ["qgis-server-http", "serve", "--verbose"]

  config-server:
    image: nginx:alpine
    networks:
    - qgis_rpc_network
    volumes:
    - type: bind
      source: "${PWD}/tests/"
      target: /usr/share/nginx/html
      read_only: true

networks:
  qgis_rpc_network:
    driver: bridge
