version: "3.9"

services:
  worker:
    image: qgis-services:release
    networks:
    - qgis_rpc_network
    volumes:
    - { type: bind, source: "${PWD}/tests/", target: /opt/qgis-services }
    command: ["qgis-server-rpc", "serve", "-C", "/opt/qgis-services/config.toml"]
  
networks:
  qgis_rpc_network:
    driver: bridge
