#-------------
# Build
#-------------

.build-docker:
  image: ${REGISTRY_URL}/factory-ci-runner:build-package
  stage: docker
  script:
  - make -C docker build deliver FLAVOR=$QGIS_FLAVOR BUILD_TARGET=ci_build
  - make -C docker build-front deliver-front FLAVOR=$QGIS_FLAVOR FRONT_BUILD_TARGET=ci_front
  environment:
    name: snap
  artifacts:
    paths:
    - "docker/factory.manifest"
    - "docker/front.manifest"
  only:
    refs:
    - tags
    - main
  tags:
  - factory-dind

build-docker:release:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: release

build-docker:ltr:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: ltr

