services:
  qgis-rpc:
    image: 3liz/qgis-services:qgis-ltr-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      CONF_LOGGING__LEVEL: debug
      CONF_WORKER__NAME: worker
      CONF_WORKER__PROJECTS__SEARCH_PATHS: >-
        { 
          "/": "/qgis-projects/france_parts"
        }
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    command: ["qgis-server-rpc", "serve"]
  web:
    image: 3liz/qgis-services:qgis-ltr-eager
    environment:
      CONF_LOGGING__LEVEL: trace
      CONF_BACKENDS__BASIC__TITLE: "Basic backends"
      CONF_BACKENDS__BASIC__ADDRESS: "tcp://qgis-rpc"
      CONF_BACKENDS__BASIC__ROUTE: "/"  
      # publish the wfs3 api endpoint 
      CONF_BACKENDS__BASIC__API: >- 
          [
            {"endpoint": "wfs3", "name": "Features OGC Api (WFS3)"}
          ]
    ports:
    - 127.0.0.1:9080:9080
    command: ["qgis-server-http", "serve"]

