

[logging]
level = "INFO"


# Remote configuration settings
[admin_http]
#
# External configuration Url
#
# The server will issue a GET method against this url at startup.
# The method should returns a valid configuration fragment.
# Note that this overrides all local settings.
#url =   	# Optional

#
# SSL configuration
#
[admin_http.ssl]
#
# CA file
#cafile =   	# Optional
#
# SSL/TLS  key
#
# Path to the SSL key file
#certfile =   	# Optional
#
# SSL/TLS Certificat
#
# Path to the SSL certificat file
#keyfile =   	# Optional


# Remote configuration settings
[admin_config_url]
#
# External configuration Url
#
# The server will issue a GET method against this url at startup.
# The method should returns a valid configuration fragment.
# Note that this overrides all local settings.
#url =   	# Optional

#
# SSL configuration
#
[admin_config_url.ssl]
#
# CA file
#cafile =   	# Optional
#
# SSL/TLS  key
#
# Path to the SSL key file
#certfile =   	# Optional
#
# SSL/TLS Certificat
#
# Path to the SSL certificat file
#keyfile =   	# Optional


[resolvers]

#
# List of Qgis pool backends
#
# DNS resolver config
# 
# Resolver for DNS resolution that may resolve
# to multiple ips.
# 
[[resolvers.pools]]
#
# Unique label
#
# Unique resolver label. The label must be compatible with an url path component.
#label =   	# Required
#
# Must be set to 'dns'
#type =   	# Required
#
# Host name
#host =   	# Required
#
# Service port
port = 23456
#
# Check for ipv6
ipv6 = false
#
# Use ssl connection
use_ssl = false
#
# SSL certificats
ssl = "cafile=None certfile=None keyfile=None"

#
# List of Qgis pool backends
#
# Resolver for socket resolution
[[resolvers.pools]]
#
# Unique label
#
# Unique resolver label. The label must be compatible with an url path component.
#label =   	# Required
#
# Must be set to 'socket'
#type =   	# Required
#address =   	# Required
use_ssl = false
#
# SSL certificats
ssl = "cafile=None certfile=None keyfile=None"

